base_url = "https://bitdevscordoba.github.io"
title = "BitDevs Córdoba"
description = "BitDevs Córdoba es una comunidad en el área de Córdoba Capital para aquellos interesados en discutir y participar en la investigación y desarrollo de Bitcoin y protocolos relacionados."
compile_sass = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
build_search_index = false

[markdown]
highlight_code = true
external_links_target_blank = true

[extra]
icons = [
  {icon = "github", link = "https://github.com/bitdevscordoba/bitdevscordoba.github.io"}
]

