base_url = "https://bitdevsmadrid.github.io"
title = "BitDevs Madrid"
description = "BitDevs Madrid es una comunidad en Madrid para aquellos interesados en discutir y participar en la investigación y desarrollo de Bitcoin y protocolos relacionados."
compile_sass = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
build_search_index = false

[markdown]
highlight_code = true
external_links_target_blank = true

[extra]
icons = [
  {icon = "github", link = "https://github.com/bitdevsmadrid/bitdevsmadrid.github.io"}
]

